// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdzgqctjualzomdetqsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkemdxY3RqdWFsem9tZGV0cXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTQ2MTgsImV4cCI6MjA2MTUzMDYxOH0.GL04ruEubAf1ZtJ55WENSGIoponnb_zZ94kAy5XqWKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);